# Generated by Django 5.1.4 on 2025-04-13 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('CollegeID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('strength', models.IntegerField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('TeacherID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=150)),
                ('Qualification', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qualification', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('CollegeID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app4.college')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subjectCode', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('credits', models.IntegerField()),
                ('Teacher', models.ManyToManyField(to='app4.teacher')),
            ],
        ),
    ]
