# Generated by Django 5.1.4 on 2025-04-11 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('CollegeID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('strength', models.IntegerField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Qualification', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('CollegeID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app2.college')),
            ],
        ),
    ]
